// var { parseWisers } = require("./index.js");
var { parseWisers } = require("./src/index.js");

var htmlText = `
<p>下載文章總數 : 1 </p><p>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #1 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</p><p>| 2019-12-16 | 澳門郵報 | P05 |MACAU / DELTA |</p><p>澳門 | 報章 | 字數: 264words | 發行量/接觸人次: 5,800</p><p>Man claims father detained on HK-<strong>Macau</strong>-<strong>Zhuhai</strong> Bridge </p><p>    <strong>HONG KONG</strong> – <strong>Hong Kong</strong>’s Immigration Department has confirmed that it is following up on a case about a <strong>Hong Kong</strong> man who went missing, as he was heading to <strong>Macau</strong> via the <strong>Hong Kong</strong>-<strong>Zhuhai</strong>-<strong>Macau</strong> Bridge.</p><p>     The son of the missing man told Cable TV that his father was heading to <strong>Macau</strong> on Friday afternoon, when mainland authorities detained him at the bridge’s eastern artificial island.</p><p>     He lost contact after messaging his family to tell them that he had been arrested.</p><p>     <strong>Zhuhai</strong> authorities had earlier issued a notice saying they would set up checkpoints on the bridge’s eastern artificial island from December 10-22 – to maintain order for the celebrations of the 20th anniversary of <strong>Macau</strong>’s return to the motherland.</p><p>     Normally, <strong>Hong Kong</strong> people only need to go through immigration checks from <strong>Macau</strong> authorities – not mainland officials – when they use the bridge to travel to <strong>Macau</strong>.</p><p>     <strong>Hong Kong</strong>’s Immigration Department said it’s been notified of the case and has followed up through the <strong>Hong Kong</strong> Economic and Trade Office in Guangdong.</p><p>     The <strong>Hong Kong</strong> police also said they’ve been notified, but the Security Bureau said it’s not appropriate for the <strong>Hong Kong</strong> government to interfere in the law enforcement activities of other jurisdictions.</p><p>     <strong>Hong Kong</strong>’s Security Bureau said it would handle cases under the existing mechanism, which requires the mainland and <strong>Hong Kong</strong> governments to notify each other if they make criminal arrests or prosecutions against residents from the other jurisdiction.</p><p>     – RTHK, MPD </p><p>文章編號: 201912160471243 </p><p>本內容經慧科的電子服務提供。以上內容、商標和標記屬慧科、相關機構或版權擁有人所有，並保留一切權利。使用者提供的任何內容由使用者自行負責，慧科不會對該等內容、版權許可或由此引起的任何損害 / 損失承擔責任。 </p><p>慧科訊業有限公司 查詢請電: (852) 2948 3888 電郵速遞: info@wisers.com 網址: http://www.wisers.com </p><p>慧科訊業有限公司（2019）。版權所有，翻印必究。 </p>`

global.die = function(message) {
  console.log(message);
  process.exit();
};

var result = parseWisers({ text: htmlText, type: "DOC" });
console.log(result);
